# This spec file was generated by KDevelop 
# Please report any problem to KDevelop Team <kdevelop-devel@kdevelop.org> 
# Thanks to Matthias Saou for his explanations on http://freshrpms.net/docs/fight.html

Name: qmmp
Version: 0.1.2
Release: %mkrel 1
#Vendor: 
Copyright: GPL
Summary: Qt-based multimedia player
Group: Multimedia
#Packager: 
BuildRoot:  %{_tmppath}/%{name}-root 
Source: http://www.ylsoftware.com/files/qmmp-0.1.2.tar.bz2
Requires: libflac8
Requires: libmad0
Requires: jackit
Requires: libffmpeg51 
Requires: libmpcdec5
Requires: libvorbis0
Requires: libvorbisfile3
Requires: libogg0
Requires: libflac8
Requires: libsamplerate0
Requires: alsa-lib
Requires: qt4-common

%description
This program is an audio-player, written with help of Qt library.

%prep
%setup -q

%build
/usr/lib/qt4/bin/qmake
make

%install
rm -rf %{buildroot}
%makeinstall INSTALL_ROOT=/%{buildroot}/usr

%clean
rm -rf %{buildroot}

%files
%defattr(0755,root,root,0755)
%{_bindir}/qmmp
%{_bindir}/qmmp.real
%defattr(0644,root,root,0755)
%dir %{_libdir}/qmmp
%dir %{_libdir}/qmmp/Input
%dir %{_libdir}/qmmp/Output
%{_libdir}/libqmmp.*
%{_libdir}/qmmp/Input/*.so
%{_libdir}/qmmp/Output/*.so


